
/*
 * GPIO.h
 *
 * Created: 8/7/2021 2:02:21 PM
 *  Author: 
 */ 
#ifndef GPIO_H_
#define GPIO_H_
#include "STD_TYPES.h"
#include "UTILES.h"
#include "GPIO_LOCAL.h"
#include "GPIO_CONFIG.h"

void GPIO_INIT_PORT_DIRECTION(UINT8 PORT , UINT8 DIRECTION);
void GPIO_WRITE_PORT_VALUE(UINT8 PORT , UINT8 VALUE);
UINT8 GPIO_READ_PORT_VALUE(UINT8 PORT);

void GPIO_INIT_PIN_DIRECTION(UINT8 PORT ,UINT8 PINno, UINT8 DIRECTION);
void GPIO_WRITE_PIN_VALUE(UINT8 PORT ,UINT8 PINno , UINT8 VALUE);
UINT8 GPIO_READ_PIN_VALUE(UINT8 PORT ,UINT8 PINno);


#endif /* GPIO_H_ */

